name: cecolfes
favicon: null
layout_spectrum: 0.36769
typography_spectrum: 0.8313593361526728
title: Centro Colombiano de Fertilidad
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0b56a3'
    - '#1cadd9'
    - '#eb7541'
    - '#94b5d6'
  brandStrength: 0.25714451912790537
  lightness: 0.9713627807796001
  saturation: 0.7193207098171115
  rhythmicContrast: 0.30606223247013986
purpose: []
